worlds:
  logLevel: INFO
  example:
    keepSpawnInMemory: false
    preventNewChunks: true
    preventChunkSaves: true
    keepLoaded:
      area1:
        x1: -10
        z1: -10
        x2: 9
        z2: 9